const express = require('express');
const { authenticate, validateBody,validateParams } = require('../../middlewares');
const { taskValidator } = require('../../validators');
const { TaskController } = require('../../controllers');
const { TaskService } = require('../../services');
const { TaskRepository } = require('../../repository');
const routes=express.Router();
const taskRepository=new TaskRepository();
const taskService= new TaskService(taskRepository);
const taskController=new TaskController(taskService);
routes.post('/',authenticate,validateBody(taskValidator.taskInfo),taskController.createTask.bind(taskController));
routes.get('/',authenticate,validateBody(taskValidator.getFilters),taskController.getTask.bind(taskController));
routes.put('/:id',authenticate,validateParams(taskValidator.taskId),validateBody(taskValidator.updateTask),taskController.updateTask.bind(taskController));
routes.delete('/:id',authenticate,validateParams(taskValidator.taskId),taskController.deleteTask.bind(taskController));
module.exports=routes;